# For every commit or tag that is pushed, but image from it and push this to docker hub

name: Build and Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      VERSION: 2.6.0
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          servers: |
            [{
                "id": "github-packages",
                "username": "${{ secrets.RELEASE_USERNAME }}",
                "password": "${{ secrets.RELEASE_TOKEN }}"
            }]
          repositories: '[{ "id": "github-packages", "url": "https://maven.pkg.github.com/isanteplus/isanteplus-packages", "uniqueVersion": "false" }]'
      - name: Build with Maven
        run: |
          mvn dependency:get -Dartifact=org.openmrs.distro:isanteplus:${VERSION}:zip -DrepositoryId=github-packages
          mvn dependency:get -Dartifact=org.openmrs.distro:isanteplus:${VERSION}:war -DrepositoryId=github-packages
          mvn dependency:copy -Dartifact=org.openmrs.distro:isanteplus:${VERSION}:zip -DoutputDirectory=/openmrs/downloaded
          mvn dependency:copy -Dartifact=org.openmrs.distro:isanteplus:${VERSION}:war -DoutputDirectory=/openmrs/distribution/openmrs_webapps
      - name: action-zip
        uses: montudor/action-zip@v0.1.1
        with:
          args: unzip -qq /openmrs/downloaded/isanteplus-${VERSION}.zip -d /openmrs/distribution/openmrs_modules
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: ./openmrs-server
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: isanteplus/isanteplus-packages/isanteplus-server
          tag_with_ref: true
          tag_with_sha: false
          add_git_labels: true
